# Generated by Django 4.0 on 2021-12-11 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=150, unique=True, verbose_name='Адрес')),
                ('rate', models.FloatField(null=True, verbose_name='Рейтинг')),
                ('count_places', models.IntegerField(verbose_name='Количество мест')),
                ('parking_price', models.IntegerField(verbose_name='Цена за день')),
            ],
        ),
    ]
