# Generated by Django 3.2 on 2021-12-14 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parkings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='parking',
            name='test_field',
            field=models.IntegerField(default=0, verbose_name='Цена за день'),
        ),
    ]
